### ISSUE TITLE
ymsp not being executed as node script

### ISSUE THREAD

**Issue by prurph** [leonzalion/yabai-master-stack-plugin#1]
I've installed ymsp and it's on my path. Node is also on my path (I'm using nvm). When I try to run commands I get errors like

```
line 1: import: command not found
```

basically indicating the file is not being run by node. If I do `node ymsp` the command works properly, although not via skhd (it complains it can't find the ymsp module--probably subshell PATH issues).

Is this expected?

**Comment by leonsilicon** [comment]
Hm, I haven't encountered that error, but I suspect it's because I haven't added a shebang at the top of my `run.ts` file. I've released a new version (1.0.8) that will hopefully solve this issue; you can upgrade to this version with `npm update -g yabai-master-stack-plugin`

As for the PATH issue, I also experienced that when using Karabiner, and this is what helped me fix it: https://docs.brew.sh/FAQ#my-mac-apps-dont-find-homebrew-utilities (in addition to the brew global path, I also added the path of the global npm registry).

Let me know if the new version works for you!

**Comment by prurph** [comment]
Thanks for the quick response—the shebang does work and also fixes the module loading.

It's not immediately clear to my why the module loading works now; previously I was using skhd to call `/usr/bin/env node ymsp ...` as a workaround and it couldn't find the module. 😕 

At any rate I can just `ymsp` now from skhd, thanks!
